easy_admin:
    site_name: '<img src="/build/images/logo-lafabricadegomas-200.png" style="max-width:70px" />'
    design:
        brand_color: '#1ABC9C'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Event:
            class: App\Entity\Event
            help: 'Administración de eventos'
            label: 'Eventos'
            list:
                title: "Eventos"
                actions:
                    - { name: 'new', label: 'Añadir evento'}
                    - { name: 'edit', label: 'Editar'}
                    - { name: 'delete', label: 'Borrar'}
                fields:
                    - { property: 'title', label: 'Título' }
                    - { property: 'subtitle', label: 'Subtítulo'}
                    - { property: 'startedAt', label: 'Fecha Inicio' , type: 'date'}
                    - { property: 'endedAt', label: 'Fecha Fin' , type: 'date'}

