easy_admin:
    site_name: '<img src="/build/images/logo-lafabricadegomas-200.png" style="max-width:70px" />'
    design:
        brand_color: '#1ABC9C'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        EventPhoto:
            class: App\Entity\EventPhoto
            help: 'Imágenes de eventos'
            label: 'Fotos de eventos'
            list:
                title: "Fotos de Eventos"
                actions:
                    - { name: 'new', label: 'Añadir evento'}
                    - { name: 'edit', label: 'Editar'}
                    - { name: 'delete', label: 'Borrar'}
                fields:
                    - { property: 'title', label: 'Título' }
                    - { property: 'image', type: 'image', base_path: '%app.path.event_images%' }
            form:
                form:
                    title: "Añadir / Editar Fotos de Evento"
                fields:
                    - title
                    - { property: 'imageFile', type: 'vich_image' }
                    - event
        Event:
            class: App\Entity\Event
            help: 'Administración de eventos'
            label: 'Eventos'
            list:
                title: "Eventos"
                actions:
                    - { name: 'new', label: 'Añadir evento'}
                    - { name: 'edit', label: 'Editar'}
                    - { name: 'delete', label: 'Borrar'}
                fields:
                    - { property: 'title', label: 'Título' }
                    - { property: 'subtitle', label: 'Subtítulo'}
                    - { property: 'startedAt', label: 'Fecha Inicio' , type: 'date'}
                    - { property: 'endedAt', label: 'Fecha Fin' , type: 'date'}
                    - { property: 'image', type: 'image', base_path: '%app.path.event_images%' }
            form:
                form:
                    title: "Añadir / Editar Eventos"
                fields:
                    - title
                    - subtitle
                    - description
                    -
                        property: 'eventPhotos'
                        type: 'collection'
                        type_options:
                            entry_type: App\Form\EventPhotoFormType
                            allow_delete: false
                            allow_add: true
                            by_reference: false

